---

- name: Tomcat - Install
  include_tasks: install.yml
  when: tcat_install | bool

- name: Tomcat - Deploy application
  include_tasks: deploy.yml
  when: tcat_deploy | bool

- name: Tomcat - Restart
  include_tasks: restart.yml
  when: tcat_restart | bool

